name: 'Deploy'
on:
  workflow_call:
    inputs:
      commit-sha:
        required: true
        type: string
        description: 'SHA of latest commit which is being deployed'
      digest:
        required: true
        type: string
        description: 'Docker Image Digest to deploy'
      environment:
        required: true
        type: string
        description: 'Environment name which is being deployed to'
      environment-url:
        required: false
        type: string
        description: 'Environment url identifying where service is running'
      gcloud-deploy-region:
        required: true
        type: string
        description: 'Region to deploy the GCloud Run instance to'
      gcloud-service-account:
        required: true
        type: string
        description: 'GCloud Service Account to authenticate as, e.g. github-actions@...'
      gcloud-workload-identity-provider:
        required: true
        type: string
        description: 'GCloud Identity Provider id to use for federated authentication'
      github-repository:
        required: true
        type: string
        description: 'Name of GitHub repository'
      service-name:
        required: true
        type: string
        description: 'Name of the service, must match the GCloud Run instances name'
    secrets:
      gcloud-deploy-project:
        required: true
        description: 'GCloud Project ID for the environment deployed to'
      gcloud-docker-image-url:
        required: true
        description: 'May contain secrets, therefore it is located under secrets'
      slack-webhook-url:
        required: true

concurrency:
  group: deploy_${{ inputs.environment }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: ${{ inputs.environment-url }}
    permissions:
      id-token: 'write'
    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        id: auth
        with:
          workload_identity_provider: ${{ inputs.gcloud-workload-identity-provider }}
          service_account: ${{ inputs.gcloud-service-account }}
      - name: Deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ inputs.service-name }}
          image: ${{ secrets.gcloud-docker-image-url }}@${{ inputs.digest }}
          region: ${{ inputs.gcloud-deploy-region }}
          project_id: ${{ secrets.gcloud-deploy-project }}
          flags: --project=${{ secrets.gcloud-deploy-project }}

  add-tag:
    needs: deploy
    name: Add Tag
    runs-on: ubuntu-latest
    permissions:
      id-token: 'write'
    steps:
      - uses: go-fjords/add-gcloud-artifact-docker-tag@v3
        with:
          gcloud-service-account: ${{ inputs.gcloud-service-account }}
          gcloud-workload-identity-provider: ${{ inputs.gcloud-workload-identity-provider }}
          gcloud-docker-image-url: ${{ secrets.gcloud-docker-image-url }}
          digest: ${{ inputs.digest }}
          new-tag: ${{ inputs.environment }}

  notify-slack-of-deploy:
    needs: deploy
    if: ${{ always() && !cancelled() }}
    name: Notify Slack of deploy status
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.slack-webhook-url }}
      SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
      SLACK_CLOUD_RUN_URL: https://console.cloud.google.com/run/detail/${{ inputs.gcloud-deploy-region }}/${{ inputs.service-name }}/metrics?project=${{ secrets.gcloud-deploy-project }}
      SLACK_LOGS_URL: https://console.cloud.google.com/logs/viewer?advancedFilter=resource.type%20%3D%20%22cloud_run_revision%22%0Aresource.labels.service_name%20%3D%20%22${{ inputs.service-name }}%22%0Aresource.labels.location%20%3D%20%22${{ inputs.gcloud-deploy-region }}%22%0A%20severity%3E%3DDEFAULT&${{ secrets.gcloud-deploy-project }}
      SLACK_COMMIT_URL: https://github.com/go-fjords/${{ inputs.github-repository }}/commit/${{ inputs.commit-sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.commit-sha }}
      - name: Generate commit message summary
        id: generate-commit-summary
        run: |
          commitSummary=$(git log -1 --pretty=%B | head -n 1 | jq ".")
          commitAuthor=$(git log -1 --pretty=%an)
          echo "::set-output name=commitSummary::$commitSummary"
          echo "::set-output name=commitAuthor::$commitAuthor"
      - name: Notify Slack regarding successfull deploy
        if: ${{ needs.deploy.result == 'success' }}
        uses: slackapi/slack-github-action@v1.22.0
        with:
          payload: "{\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\":rocket: Deployed *${{ inputs.service-name }}* to *${{ inputs.environment }}* by *${{ github.actor }}*\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"<${{ env.SLACK_CLOUD_RUN_URL }}|cloud run> - <${{ env.SLACK_LOGS_URL }}|logs> - <${{ env.SLACK_COMMIT_URL }}|commit>\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"${{ steps.generate-commit-summary.outputs.commitSummary }}\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"Authored by: ${{ steps.generate-commit-summary.outputs.commitAuthor }}\"}}]}"
      - name: Notify Slack regarding failed deploy
        if: ${{ always() && needs.deploy.result == 'failure' }}
        uses: slackapi/slack-github-action@v1.22.0
        with:
          payload: "{\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\":boom: Failed to deploy *${{ inputs.service-name }}* to *${{ inputs.environment }}* by *${{ github.actor }}*\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"<${{ env.SLACK_CLOUD_RUN_URL }}|cloud run> - <${{ env.SLACK_LOGS_URL }}|logs> - <${{ env.SLACK_COMMIT_URL }}|commit>\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"${{ steps.generate-commit-summary.outputs.commitSummary }}\"}},{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"Authored by: ${{ steps.generate-commit-summary.outputs.commitAuthor }}\"}}]}"

